[package]
name = "elb-log-transform"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
clap = { version = "4.5.17", features = ["derive"] }
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.128"
